name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: docker init
      run: docker build -t noderollup:latest ./

    - name: prepare
      run: docker run -t noderollup:latest -v $(pwd):/app -w /app pwsh -Command 'npm install'
           
    - name: Build JS
      run: docker run --rm -t --user `id -u`:`id -g` -v $(pwd):/app -w /app noderollup:latest rollup app.js -f iife -o ./public/app.min.js -p @rollup/plugin-node-resolve --compact
      
    - name: Run distcheck
      run: zip release${{ env.NEXT_VERSION }}.zip actions/* public/* views/* helpers/html/* Module.php manifest.json
    
    - name: Dev-Build
      on:
        create:
          tags:
            - v*
         
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
       artifacts: "release${{ env.NEXT_VERSION }}.zip"
       token: ${{ secrets.GITHUB_TOKEN }}
