name: Makefile CI

on:  
  push:
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: docker init
      run: docker build -t noderollup:latest ./

    - name: prepare
      run: docker run -t noderollup:latest -v $(pwd):/app -w /app pwsh -Command 'npm install'
           
    - name: Build JS
      run: docker run --rm -t --user `id -u`:`id -g` -v $(pwd):/app -w /app noderollup:latest rollup app.js -f iife -o ./public/app.min.js -p @rollup/plugin-node-resolve --compact
      
    - name: Run distcheck
      run: zip release${{ env.NEXT_VERSION }}.zip actions/* public/* views/* helpers/html/* Module.php manifest.json
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: public
        asset_name: mything
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
