name: Makefile CI

on:  
  push:
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker init
      run: docker build -t noderollup:latest ./

    - name: Prepare docker image
      run: docker run -t noderollup:latest -v $(pwd):/app -w /app pwsh -Command 'npm install'
           
    - name: Build JS
      run: docker run --rm -t --user `id -u`:`id -g` -v $(pwd):/app -w /app noderollup:latest rollup app.js -f iife -o ./public/app.min.js -p @rollup/plugin-node-resolve --compact
      
    - name: Create module directory
      run: mkdir ${{ github.event.repository.name }}

    - name: Copy 
      run: cp -r actions/ public/ views/ helpers/ Module.php manifest.json ${{ github.event.repository.name }}
 
    - name: Build zip release file
      run: zip -r release.zip ${{ github.event.repository.name }}
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: release.zip
        asset_name: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
