name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: prepare
      run: docker run --rm -it -v $(shell pwd):/app -w /app $(DOCKER_IMAGE) npm install
      
    - name: Build JS
      run: docker run --rm -it --user `id -u`:`id -g` -v $(shell pwd):/app -w /app $noderollup:latest rollup app.js -f iife -o ./public/app.min.js -p @rollup/plugin-node-resolve --compact
      
    - name: docker init
      run: docker build -t noderollup:latest ./
      
    - name: Run distcheck
      run: zip release${{ env.NEXT_VERSION }}.zip actions/* public/* views/* helpers/html/* Module.php manifest.json
